"""Create table creditos

Revision ID: 8833192f009d
Revises: 
Create Date: 2025-09-13 13:05:18.496675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8833192f009d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente', sa.String(length=120), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tasa_intereses', sa.Float(), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('fecha_otorgamiento', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditos')
    # ### end Alembic commands ###
